site_name: WXOHandson
theme:
  font:
    text: IBM Plex Sans JP
  palette:
    scheme: default
    accent: black
  name: material
  features:
    - tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate
nav:
- Agenda: agenda.md
- Technical Lab1: lab1.md
- Technical Lab2: lab2.md

extra_css:
  - stylesheets/extra.css

extra:
  generator: false


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format