site_name: WXOHandson
plugins:
  - glightbox
theme:
  font:
    text: IBM Plex Sans JP
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  name: material
  features:
    - tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate
nav:
- Agenda: agenda.md
- Hello world: lab1.md
- Skill flow: lab2.md
- Automation Builder: lab3.md
- OpenAPI Builder: OpenAPI.md
- GenAI: GenAI.md
- AI Assistant: AIAssistant.md

extra_css:
  - stylesheets/extra.css

extra:
  generator: false


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format